baseURL = 'https://the29a.github.io/'
languageCode = 'en-us'
title = '29a µ blog'
theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
  
    identifier = "projects"
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
  
    identifier = "tags"
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4
  
  [[menu.main]]
    name = "About"
    pre = "<span data-feather='target'></span>"
    url = "/about/"
    weight = 5  
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/the29a"
    weight = 6
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = ""

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = ""

  # Description to display on homepage
  description = "infosec and something else"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["it", "cybersecurity", "hacking"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "the29a"

  pygmentsStyle = "monokai"


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
